config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get  'about', to: 'pages#about'

  get 'tes', to: 'articles#tes'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { minimum: 10, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 100 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false, message: 'Telah terdaftar !' },
                       length: { minimum: 3 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    length: { maximum: 105 },
                    uniqueness: { case_sensitive: false, message: 'Telah terdaftar !' },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit show update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def create
    # debugger
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:success] = 'Create article success'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @article.update(article_params)
      flash[:success] = 'Succesfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:danger] = 'Deleted Succesfully'
      redirect_to articles_path
    end
  end

  def tes; end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


    def home

    end
    
    def about

    end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    # debugger
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to alpha blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'Your account was updated successfully !'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @users = User.find(params[:id])
    @user_articles = @users.articles.paginate(page: params[:page], per_page: 3)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def gravatar_for(user, option = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'img-circle')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
<% obj.each do |article|  %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to article.title, article_path(article) %>
                </div>    
                <div class="article-body">
                    <%= truncate(article.description,length:100) %>
                </div>
                <div class="article-details">
                    <small> Created by : <%= article.user.username if article.user %>, Created date : <%= time_ago_in_words(article.created_at)%> ago, Updated at : <%= time_ago_in_words(article.updated_at)%> ago</small>
                </div>
                <div>
                    <%= link_to 'Edit This Article',edit_article_path(article),class:"btn btn-success btn-xs" %>
                    <%= link_to 'Delete This Article',article_path(article),method: :delete,data:{confirm:"are you sure?"},class:"btn btn-danger btn-xs" %>
                </div>
            </div>
        </div>    
    </div>
 <% end  %>

app/views/articles/_form.html.erb
<%= render 'shared/error',obj:@article %>


<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class:"form-horizontal",role:"form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :title%>
            </div>    
            <div class="col-sm-6">
                <%= f.text_field :title,class:"form-control",placeholder:"Title of article",autofocus:true %>
            </div>
       </div>

       <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :description%>
            </div>    
            <div class="col-sm-6">
                <%= f.text_field :description,rows: 10,class:"form-control",placeholder:"Description of article",autofocus:true %>
            </div>
       </div>
       
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class:"btn btn-primary btn-lg" %>
            </div>
        </div>

        <% end %>

    </div>
</div>

app/views/articles/edit.html.erb
<h3 class="text-center"> Edit username </h3>

<%= link_to 'Home Page', root_path %>

<%= render 'form' %>

<%= link_to 'Index',articles_path %>

app/views/articles/index.html.erb
<h2 class="text-center"> All articles </h2>

<div align="center">
    <%= will_paginate%>
</div>
<%= render  "articles",obj:@articles%>

 

app/views/articles/new.html.erb
<h3 class="text-center"> Add username </h3>

<%= link_to 'Home Page', root_path %>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center">
    Title : <%= @article.title %>
</h2>

<div class="well col-xs-8 col-xs-offset-2">
    <% if @article.user %>
<ul class="listing">
            <div class="row text-center">
                <div class="col-md-4 col-md-offset-4">
                    <li> Created by :</li>
                    <li><%= link_to gravatar_for(@article.user),user_path(@article.user) %></li>
                    <li class="article-title">
                        <%= link_to  @article.user.username, user_path(@article.user) %>
                    </li>
                    <li>
                        <small><%= pluralize(@article.user.articles.count,"article") if @article.user.articles%> </small>
                    </li>
                </div>
            </div>    
        </ul>
        <% end %>
    <h4 class="text-center"><strong>Description</strong></h4>
        <hr>
        <%= @article.description %>

    <div>
        <%= link_to 'Edit This Article',edit_article_path(@article),class:"btn btn-success btn-xs" %>
        <%= link_to 'Delete This Article',article_path(@article),method: :delete,data:{confirm:"are you sure?"},class:"btn btn-danger btn-xs" %>
        <%= link_to 'Index',articles_path,class:"btn btn-primary btn-xs" %>
    </div>
</div>    

app/views/articles/tes.html.erb
<h3> TEST PAGE </h3>

app/views/layouts/_footer.html.erb
    <footer class="footer">
        <div class="container">
        <small>
            Copyright &copy; By Fadel 
        </small>
        </div>

app/views/layouts/_message.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name,msg|  %>
          
            <div class="alert alert-<%= "#{name}" %>">
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, :id =>"flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# <a class="navbar-brand" id="logo" href="">Alpha Blog</a> %>
      <%= link_to 'Alpha Blog',root_path, class:"navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Articles', articles_path %></li>
        <li> <%= link_to 'New Article', new_article_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/message' %>
      <div class="container">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h4> welcome to about page </h4>

<%= link_to 'Home', root_path%>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  
    <h1> Welcome to Alpha Blog </h1>
    <%= link_to 'Sign Up', '#', class:"btn btn-danger btn-lg btn-black" %>
  <%# </div> %>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-6 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count,"error") %>
                        prohibited this article from being saved
                    </h2>
                </div>
                    <div class="panel-body">
                        <ul>
                            <%= obj.errors.full_messages.each do |msg| %>
                            <li> <%= msg %></li>
                            <% end  %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>    
    </div> 
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error',obj:@user %>

<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class:"form-horizontal",role:"form"}) do |f| %>
        <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :username%>
            </div>    
            <div class="col-sm-6">
                <%= f.text_field :username,class:"form-control",placeholder:"Username",autofocus:true %>
            </div>
       </div>

       <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :password%>
            </div>    
            <div class="col-sm-6">
                <%= f.password_field :password,class:"form-control",placeholder:"Password",autofocus:true %>
            </div>
       </div>

       <div class="form-group">
            <div class="control-label col-sm-2">
                <%= f.label :email%>
            </div>    
            <div class="col-sm-6">
                <%= f.email_field :email,class:"form-control",placeholder:"Email",autofocus:true %>
            </div>
       </div>
       
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit(@user.new_record? ? "Sign up" : "Update you accont",class:"btn btn-primary btn-lg") %>
            </div>
        </div>

        <% end %>

    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit user </h1>


<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center"> All alpha blogggers </h1>
<div align="center">
   <%= will_paginate %> 
    <%= @users.each do |user| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li><%= link_to gravatar_for(user),user_path(user) %></li>
                    <li class="article-title">
                        <%= link_to  user.username, user_path(user) %>
                    </li>
                    <li>
                        <small><%= pluralize(user.articles.count,"article") if user.articles%> </small>
                    </li>
                </div>
            </div>    
        </ul>
     <% end %>
</div>        

app/views/users/new.html.erb
<h1 align="center">Sign up user </h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @users.username %>'s page</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
            <%= gravatar_for @users,size: 150 %>
    </div>
</div>

<h4 align="center"><%= @users.username %>'s articles </h4>
<div class="text-center">
    <%= will_paginate @user_articles %>
</div>    
<%= render  "articles/articles",obj: @user_articles %>